baseURL: https://basselch.com
title: Bassel Cheaib
paginate: 12

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

build:
  writeStats: true

permalinks:
  blog: /a/:slug/
  page: /:slug/
  books: /b/:slug/

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    contentDir: content/en
    weight: 1
    menu:
      main:
        - name: About
          url: about
        - name: Now
          url: now
        - name: Blog
          url: blog
        - name: Books
          url: books
        - name: Archive
          url: archives
        - name: Search
          url: search/

  ar:
    contentDir: content/ar
    languagedirection: rtl
    weight: 2
    title: باسل شعيب
    homeInfoParams:
      Title: "مرحبًا بكم في حديقتي الرقمية"
      Content: >
        هنا ستجدون جميع المحتوى العربي من مقالات وكتب وغيرها.

        - أتمنى أن تستفيدوا منها، وإن كان لديكم أي تعليق أو إستفسار لا تترددوا في التواصل معي!
    menu:
      main:
        - name: المقالات
          url: blog
        - name: الكتب
          url: books
        - name: الأرشيف
          url: archives
        - name: البحث
          url: search/

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  description: "I'm a computer scientist who enjoys learning new stuff and sharing knowlegde with others. Currently in permanent beta: learning, improving, evolving..."
  author: Bassel Cheaib
  ShowShareButtons: true
  ShowReadingTime: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true
  comments: true
  utterances:
    repo: bassel/PWComments
    issueTerm: url
    label: PW
  images: ["cover.png"]

  mainSections: ['blog', 'books']

  homeInfoParams:
    Title: "Welcome to my digital garden"
    Content: >
      Here, you'll find all the digital content I create (articles, book notes, random thoughts, etc).

      - I hope you find some of the stuff here interesting and useful.

      - In case you have any thoughts or comments, please don't hesitate to get in touch with me!

  socialIcons:
    - name: github
      url: "https://go.basselch.com/gh"
    - name: twitter
      url: "https://go.basselch.com/tw"
    - name: telegram
      url: "https://go.basselch.com/tm"
    - name: email
      url: "https://go.basselch.com/email"
    - name: buymeacoffee
      url: "https://go.basselch.com/bmc"
    - name: Rss
      url: "index.xml"

  navSocial:
    - name: twitter
      url: "https://go.basselch.com/tw"
    - name: telegram
      url: "https://go.basselch.com/tm"
    - name: email
      url: "https://go.basselch.com/email"
    - name: Rss
      url: "index.xml"

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
